apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nour0/auth:latest # Correction apportée ici
          ports:
            - containerPort: 8200
---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: auth
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
  type: LoadBalancer