version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports:
      - "3001:6000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '0000' # Set the root password here
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_AUTH_PLUGIN: 'mysql_native_password' # Set the authentication plugin here
    ports:
      - "3305:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysqldata:
